# Generated by Django 5.0.7 on 2024-07-23 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=350)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=200)),
                ('job_type', models.CharField(max_length=100)),
                ('experience', models.CharField(max_length=20)),
                ('salary', models.CharField(blank=True, max_length=15)),
                ('qualification', models.CharField(max_length=200)),
                ('skills_required', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.employer')),
            ],
        ),
    ]
