# Generated by Django 5.0.7 on 2024-07-28 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_jobapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker',
            name='skills',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
